export const CLOUDINARY_CLOUD_NAME = "domthgc9v";
export const CLOUDINARY_UPLOAD_PRESET = "images";

export const exams = [
  {
    title: "N.C.E.E",
    desc: "The National Common Entrance Examination is for admission into Junior Secondary School (JSS 1) of Federal Government Unity Colleges.",
    image: require("../assets/images/neco.png"),
    questions: 19670,
  },
  {
    title: "B.E.C.E",
    desc: "The Basic Education Certificate Examination (BECE) is the examination conducted for candidates in their final year of Junior Secondary School.",
    image: require("../assets/images/neco.png"),
    questions: 90150,
  },
  {
    title: "J.A.M.B Exam",
    desc: "Joint Admission and Matriculation Board past questions",
    image: require("../assets/images/jamb.png"),
    questions: 63250,
  },
  {
    title: "W.A.E.C",
    desc: "West African Senior School Certificate Examination past questions",
    image: require("../assets/images/waec.webp"),
    questions: 111180,
  },
  {
    title: "POST UTME",
    desc: "Post UTME screening past questions for various institutions",
    image: null, // No image, fallback icon will show
    questions: 24120,
  },
  {
    title: "NDA",
    desc: "Prepare for the Nigerian Defence Academy Screening Test with over 4,000 past questions designed to sharpen your skills and boost your confidence.",
    image: require("../assets/images/NDA.png"),
    questions: 4500,
  },
];

export const COUNTRIES = [
  { name: "Algeria", code: "dz" },
  { name: "Angola", code: "ao" },
  { name: "Benin", code: "bj" },
  { name: "Botswana", code: "bw" },
  { name: "Burkina Faso", code: "bf" },
  { name: "Burundi", code: "bi" },
  { name: "Cameroon", code: "cm" },
  { name: "Cape Verde", code: "cv" },
  { name: "Central African Republic", code: "cf" },
  { name: "Chad", code: "td" },
  { name: "Comoros", code: "km" },
  { name: "Congo (DRC)", code: "cd" },
  { name: "Congo (Republic)", code: "cg" },
  { name: "Côte d'Ivoire", code: "ci" },
  { name: "Djibouti", code: "dj" },
  { name: "Egypt", code: "eg" },
  { name: "Equatorial Guinea", code: "gq" },
  { name: "Eritrea", code: "er" },
  { name: "Eswatini", code: "sz" },
  { name: "Ethiopia", code: "et" },
  { name: "Gabon", code: "ga" },
  { name: "Gambia", code: "gm" },
  { name: "Ghana", code: "gh" },
  { name: "Guinea", code: "gn" },
  { name: "Guinea-Bissau", code: "gw" },
  { name: "Kenya", code: "ke" },
  { name: "Lesotho", code: "ls" },
  { name: "Liberia", code: "lr" },
  { name: "Libya", code: "ly" },
  { name: "Madagascar", code: "mg" },
  { name: "Malawi", code: "mw" },
  { name: "Mali", code: "ml" },
  { name: "Mauritania", code: "mr" },
  { name: "Mauritius", code: "mu" },
  { name: "Morocco", code: "ma" },
  { name: "Mozambique", code: "mz" },
  { name: "Namibia", code: "na" },
  { name: "Niger", code: "ne" },
  { name: "Nigeria", code: "ng" },
  { name: "Rwanda", code: "rw" },
  { name: "São Tomé and Príncipe", code: "st" },
  { name: "Senegal", code: "sn" },
  { name: "Seychelles", code: "sc" },
  { name: "Sierra Leone", code: "sl" },
  { name: "Somalia", code: "so" },
  { name: "South Africa", code: "za" },
  { name: "South Sudan", code: "ss" },
  { name: "Sudan", code: "sd" },
  { name: "Tanzania", code: "tz" },
  { name: "Togo", code: "tg" },
  { name: "Tunisia", code: "tn" },
  { name: "Uganda", code: "ug" },
  { name: "Zambia", code: "zm" },
  { name: "Zimbabwe", code: "zw" },
];
